environment: dev

sealed-secrets:
  image:
    registry: docker.io
    repository: bitnami/sealed-secrets-controller

  ## @param skipRecreate Specifies whether the Sealed Secrets controller should skip recreating removed secrets
  ## Setting it to false allows to optionally restore backward compatibility in low priviledge
  ## environments when old versions of the controller did not require watch permissions on secrets
  ## for secret re-creation.
  ##
  skipRecreate: false
  ## @param keyrenewperiod Specifies key renewal period. Default 30 days
  ## e.g
  ## keyrenewperiod: "720h30m"
  ##
  keyrenewperiod: "4320h" # 6 mounths
